version: '3.5'
services:
  serverless:
    build:
      context: .
      args:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    tty: true
    stdin_open: true
    image: serverless
    container_name: serverless-${APP_NAME}
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"
      - "3001:3001"
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
