import { gql } from '@apollo/client'
import client from '../apollo/client'
import Head from 'next/head'

const LANGUAGES = gql`
  query {
    languages {
      code
      name
    }
  }
`

type Language = {
  code: number,
  name: string
}

type Props = {
  languages: Language[]
}

const Home: React.FC<Props> = ({ languages }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        {languages.map(language => (
          <li key={language.code}>{language.name}</li>
        ))}
      </ul>
    </div>
  )
}

export async function getStaticProps() {
  const { data } = await client.query({
    query: LANGUAGES
  })
  const languages = data.languages
  return {
    props: { languages },
    revalidate: 15
  }
}

export default Home